const content={

    SignIn: "سائن ان",
    EnterUserName: "صارف درج کریں",
    EnterPassword:"پاس ورڈ درج کریں",
    DeliveryDate:"ادئیگی کی تاریخ",
    Customers:"گاہک",
    CustomerName:"گاہک کا نام",
    ContactNo:"رابطے کا نمبر",
    Address:"پتہ",
    AddCustomer:"گاہک شامل کریں",
    EnterName:"نام درج کریں",
    EnterAddress:"پتہ درج کریں",
    EnterMobileNo:"موبائل نمبر درج کریں",
    SelectProduct:"مصنوعات کو منتخب کریں",
    EnterProductDetail:"مصنوعات کی تفصیل درج کریں",
    Save:"محفوظ کریں",
    ProductDetail:"مصنوعات کی تفصیل",
    Products:"مصنوعات",
    Price:"قیمت",
    Quantity: "مقدار",
    OK:"ٹھیک ہے",
    Date:"تاریخ",
    Previous: "پیچھے",
    Next:"آگے",
    Delivery:"ترسیل",
    ViewReport:"رپورٹ ملاحظہ کریں",
    AddPackagingsize:'پیکیجنگ شامل کریں',
    CustomersList:'گاہکوں کی فہرست',
    Report:'رپورٹ',
    Packging:'پیکیجنگ',
    PackgingList:'پیکیجنگ کی فہرست',
    Name:'نام',
    Amount:'رقم',
    Liter:'لیٹر',
    size:'سائز',
    WelCome:'خوش آمدید',
    NORecord:'کوئی ریکارڈ نہیں ملا',
    PleaseEnterSerialNo:'سیریل نمبر درج کریں',
    SerialNo :'سیریل نمبر'


}
export default content;